import { rm, mkdir, cp, readdir, writeFile } from 'node:fs/promises';
import { join, relative, posix } from 'node:path';
import { Glob } from 'bun';

const OUT_DIR = 'dist-desktop';
const DIST_DIR = 'dist';
const ROUTES_FILE = 'dist-routes.ts';
const APP_NAME = 'aspenini-media-tool';

type CompileTarget =
  | 'bun-darwin-arm64'
  | 'bun-darwin-x64'
  | 'bun-linux-x64'
  | 'bun-linux-arm64'
  | 'bun-windows-x64';

const TARGETS: Array<{ suffix: string; target: CompileTarget }> = [
  { suffix: 'darwin-arm64', target: 'bun-darwin-arm64' },
  { suffix: 'darwin-x64', target: 'bun-darwin-x64' },
  { suffix: 'linux-x64', target: 'bun-linux-x64' },
  { suffix: 'linux-arm64', target: 'bun-linux-arm64' },
  { suffix: 'windows-x64', target: 'bun-windows-x64' },
];

function mimeType(path: string): string {
  if (path.endsWith('.html')) return 'text/html; charset=utf-8';
  if (path.endsWith('.js')) return 'application/javascript; charset=utf-8';
  if (path.endsWith('.css')) return 'text/css; charset=utf-8';
  if (path.endsWith('.svg')) return 'image/svg+xml';
  if (path.endsWith('.png')) return 'image/png';
  if (path.endsWith('.ico')) return 'image/x-icon';
  if (path.endsWith('.json') || path.endsWith('.map')) return 'application/json';
  if (path.endsWith('.txt')) return 'text/plain; charset=utf-8';
  return 'application/octet-stream';
}

async function copyPublic(): Promise<void> {
  const publicDir = 'public';
  let entries: string[];
  try {
    entries = await readdir(publicDir);
  } catch {
    return;
  }
  for (const entry of entries) {
    await cp(join(publicDir, entry), join(DIST_DIR, entry), { recursive: true });
  }
}

async function buildSite(): Promise<void> {
  console.log('Building site into dist/...');
  await rm(DIST_DIR, { recursive: true, force: true });
  await mkdir(DIST_DIR, { recursive: true });

  const result = await Bun.build({
    entrypoints: ['index.html'],
    outdir: DIST_DIR,
    target: 'browser',
    minify: true,
    sourcemap: 'linked',
    naming: {
      entry: '[dir]/[name].[ext]',
      asset: 'assets/[name]-[hash].[ext]',
      chunk: 'assets/[name]-[hash].[ext]',
    },
  });

  if (!result.success) {
    console.error('Site build failed:');
    for (const log of result.logs) console.error(log);
    process.exit(1);
  }

  await copyPublic();
}

async function writeDistRoutes(): Promise<void> {
  const glob = new Glob('**/*');
  const files: string[] = [];
  for await (const path of glob.scan({ cwd: DIST_DIR, onlyFiles: true })) {
    if (path.endsWith('.map')) continue;
    files.push(path);
  }
  files.sort();

  const imports = files
    .map((path, index) => {
      const importPath = `./${posix.join(DIST_DIR, path)}`;
      return `import asset${index} from ${JSON.stringify(importPath)} with { type: "file" };`;
    })
    .join('\n');

  const routes = files
    .map((path, index) => {
      const urlPath = `/${path.split(/[/\\]/).join('/')}`;
      return `  ${JSON.stringify(urlPath)}: { file: asset${index}, type: ${JSON.stringify(mimeType(path))} },`;
    })
    .join('\n');

  const source = `// @ts-nocheck
// Auto-generated by build-desktop.ts. Do not edit.
${imports}

export type DistRoute = { file: string; type: string };

export const distRoutes: Record<string, DistRoute> = {
${routes}
};
`;

  await writeFile(ROUTES_FILE, source);
  console.log(`Generated ${ROUTES_FILE} (${files.length} assets).`);
}

async function compile(outfile: string, target?: CompileTarget): Promise<void> {
  const result = await Bun.build({
    entrypoints: ['./server.ts', './server-worker.ts'],
    compile: {
      outfile,
      ...(target ? { target } : {}),
    },
    minify: true,
    sourcemap: 'linked',
  });

  if (!result.success) {
    console.error(`Desktop build failed for ${outfile}:`);
    for (const log of result.logs) console.error(log);
    process.exit(1);
  }

  console.log(`  ${relative(process.cwd(), outfile)}`);
}

async function main(): Promise<void> {
  const buildAll = process.argv.includes('--all');

  await buildSite();
  await writeDistRoutes();
  await rm(OUT_DIR, { recursive: true, force: true });
  await mkdir(OUT_DIR, { recursive: true });

  if (buildAll) {
    console.log(`Building desktop executables for all platforms into ${OUT_DIR}/`);
    for (const { suffix, target } of TARGETS) {
      const ext = suffix.startsWith('windows') ? '.exe' : '';
      await compile(join(OUT_DIR, `${APP_NAME}-${suffix}${ext}`), target);
    }
  } else {
    console.log(`Building desktop executable into ${OUT_DIR}/`);
    await compile(join(OUT_DIR, APP_NAME));
  }

  console.log('Desktop build complete.');
}

await main();
